### ISSUE TITLE
Unrequested columns in the advance search notebook

### ISSUE THREAD

**Issue by JPCalderon** [NOAO/nat-nb#2]
Hello! thank you for the notebooks templeates.

i've started last week to used the OIR Astro Lab, with api version 3.0,
and today i realase that the version change to 4.0. 
This [notebook](https://github.com/NOAO/nat-nb/blob/master/advanced-search.ipynb) worked fine until today, and i have problems to the output table file, after this command:

`df = pd.read_json ( json.dumps ( response.json() ) )`

appear in the df pandas, some columns that i didn't ask for:
HEADER, META, PARAMETERS, RESULTS

i used this workaround, to use the same notebook:

```df = df.iloc[1:]
df = df.drop('HEADER', axis=1)
df = df.drop('META', axis=1)
df = df.drop('PARAMETERS', axis=1)
df = df.drop('RESULTS', axis=1)
df = df.reset_index(drop=True)
``` 

With the change of api version, there are to change something in the notebook or in the JASON file?

Thank you for your time.

**Comment by pothiers** [comment]
We released a new [AstroArchive API](https://astroarchive.noao.edu/api/docs/) yesterday. That bumped the API version because there are potential backwards incompatible changes.  It also returns  information about the search in the first element of the list returned in the response. I will modify the notebooks soon so that they work with the new version.  Check back here for information on the changes and how you can make use of the additional returned info.  Its possible that we will add 

In the meantime your workaround is a reasonable one.  Thanks for sharing it!
You could also change `pd.read_json(json.dumps(requests.post(apiurl,json=jj).json()))` to `pd.read_json(json.dumps(requests.post(apiurl,json=jj).json()[1:]))`.  This will simply throw away the first element that contains metadata you don't care about.

**Comment by pothiers** [comment]
Notebooks updated to match AstroArchive Release 2020.09.  Open a new issue you have any other problems.
